include: package:lint/analysis_options.yaml

linter:
  rules:
    constant_identifier_names: false
    directives_ordering: false
    file_names: false
    unnecessary_this: false
    prefer_final_in_for_each: false
    avoid_classes_with_only_static_members: false
    avoid_relative_lib_imports: false
    avoid_function_literals_in_foreach_calls: false
    use_setters_to_change_properties: false

analyzer:
  errors:
    missing_required_param: error
    parameter_assignments: error